import { defineConfig } from "tsdown";
import pluginBabel from "@rollup/plugin-babel";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/types.ts",
    "src/components/accordion/index.ts",
    "src/components/autocomplete/index.ts",
    "src/components/badge/index.ts",
    "src/components/button/index.ts",
    "src/components/card/index.ts",
    "src/components/code/index.ts",
    "src/components/context-menu/index.ts",
    "src/components/dialog/index.ts",
    "src/components/dropdown-menu/index.ts",
    "src/components/dropdown-menu-nested/index.ts",
    "src/components/flash/index.ts",
    "src/components/highlight/index.ts",
    "src/components/href/index.ts",
    "src/components/fields/index.ts",
    "src/components/fields/altcha/index.ts",
    "src/components/fields/checkbox/index.ts",
    "src/components/fields/radio/index.ts",
    "src/components/fields/color/index.ts",
    "src/components/fields/select/index.ts",
    "src/components/fields/text/index.ts",
    "src/components/fields/textarea/index.ts",
    "src/components/fields/date/index.ts",
    "src/components/fields/file/index.ts",
    "src/components/fields/toggle/index.ts",
    "src/components/fields/range/index.ts",
    "src/components/fields/stars/index.ts",
    "src/components/fields/totp/index.ts",
    "src/components/fields/input-button/index.ts",
    "src/components/fields/wysiwyg/index.ts",
    "src/components/loader/index.ts",
    "src/components/media-preview/index.ts",
    "src/components/modal/index.ts",
    "src/components/notification/index.ts",
    "src/components/popover/index.ts",
    "src/components/portal/index.ts",
    "src/components/resizable/index.ts",
    "src/components/resize-area/index.ts",
    "src/components/separator/index.ts",
    "src/components/scroll/index.ts",
    "src/components/select-legacy/index.ts",
    "src/components/slot/index.ts",
    "src/components/snack/index.ts",
    "src/components/steps/index.ts",
    "src/components/table/index.ts",
    "src/components/tabs/index.ts",
    "src/components/toast/index.ts",
    "src/components/tooltip/index.ts",
    "src/hooks/index.ts",
    "src/lib/index.ts",
  ],
  dts: true,
  format: ["esm"],
  deps: {
    onlyBundle: [],
  },
  shims: true,
  plugins: [
    pluginBabel({
      babelHelpers: "bundled",
      parserOpts: {
        sourceType: "module",
        plugins: ["jsx", "typescript"],
      },
      plugins: ["babel-plugin-react-compiler"],
      extensions: [".js", ".jsx", ".ts", ".tsx"],
    }),
  ],
});
